import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Posts
        </h1>

        <ul className={styles.posts}>
          <li>
            <p className={styles.postsContent}>
              I'm working in Figma trying to design a new website that shows all my tweets!
            </p>
            <p className={styles.postsDate}>
              6/4/2022
            </p>
          </li>
          <li>
            <p className={styles.postsContent}>
              I'm working in Figma trying to design a new website that shows all my tweets!
            </p>
            <p className={styles.postsDate}>
              6/4/2022
            </p>
          </li>
          <li>
            <p className={styles.postsContent}>
              I'm working in Figma trying to design a new website that shows all my tweets!
            </p>
            <p className={styles.postsDate}>
              6/4/2022
            </p>
          </li>
        </ul>

        <form action="">
          <textarea className={styles.formContent} id="" cols="30" rows="10"></textarea>
          <button className={styles.formButton}>Add New Post</button>
        </form>
      </main>

      
    </div>
  )
}
